backend:
  name: github
  repo: sysmake-dev/pchs-jrotc-case-study
  branch: main

  base_url: https://github-oauth.sysmake.workers.dev
  auth_endpoint: auth

media_folder: src/assets/images/uploads
public_folder: /src/assets/images/uploads

collections:
  - name: announcements
    label: Announcements

    files:
      - name: announcements
        label: Announcements

        file: src/content/announcements.json

        fields:
          - label: Announcements
            name: announcements
            widget: list

            summary: "{{fields.title}}"

            fields:
              - label: Title
                name: title
                widget: string

              - label: Date
                name: date
                widget: string

              - label: Summary
                name: summary
                widget: text

              - label: Current
                name: current
                widget: boolean

  - name: events
    label: Events

    files:
      - name: events
        label: Events

        file: src/content/events.json

        fields:
          - label: Events
            name: events
            widget: list

            summary: "{{fields.title}}"

            fields:
              - label: Title
                name: title
                widget: string

              - label: Date
                name: date
                widget: string

              - label: Location
                name: location
                widget: string

              - label: Summary
                name: summary
                widget: text

  - name: resources
    label: Resources

    files:
      - name: resources
        label: Resources

        file: src/content/resources.json

        fields:
          - label: Resources
            name: resources
            widget: list

            summary: "{{fields.title}}"

            fields:
              - label: Category
                name: category
                widget: string

              - label: Title
                name: title
                widget: string

              - label: File
                name: file
                widget: string
