backend:
  name: github
  repo: sysmake-dev/pchs-jrotc-case-study
  branch: main

  base_url: https://github-oauth.sysmake.workers.dev
  auth_endpoint: auth

media_folder: src/assets/images/uploads
public_folder: /src/assets/images/uploads

collections:
  - name: announcements
    label: Announcements

    files:
      - label: Announcements
        name: announcements

        file: ../announcements.json

        fields:
          - label: Announcements
            name: announcements
            widget: list

            summary: "{{fields.title}}"

            fields:
              - label: Title
                name: title
                widget: string

              - label: Date
                name: date
                widget: datetime
                format: "YYYY-MM-DD"
                time_format: false

              - label: Summary
                name: summary
                widget: text

              - label: Current
                name: current
                widget: boolean
